#!/bin/bash
set -e

# ==========================================
# Configuration & Inputs
# ==========================================

echo "----------------------------------------------------------------"
echo "   Matrix (Synapse) + Postgres Installer"
echo "   Based on Will Lewis's Guide, adapted for Docker."
echo "----------------------------------------------------------------"

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo "Error: Docker is not installed. Please install Docker first."
    exit 1
fi

read -p "Enter your Matrix Domain Name (e.g., example.com): " SERVER_NAME
read -p "Enter the directory to install to [default: ./matrix-server]: " INSTALL_DIR
INSTALL_DIR=${INSTALL_DIR:-./matrix-server}

# Generate a random password for the database
DB_PASSWORD=$(openssl rand -hex 16)
echo "Generated secure Database Password: $DB_PASSWORD"

# ==========================================
# 1. Directory Setup
# ==========================================

echo "Creating installation directory at $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR/data"
mkdir -p "$INSTALL_DIR/db_data"

cd "$INSTALL_DIR"

# ==========================================
# 2. Create Docker Compose File
# ==========================================

echo "Generating docker-compose.yml..."
cat > docker-compose.yml <<EOF
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=$SERVER_NAME
      - SYNAPSE_REPORT_STATS=yes
      - UID=991
      - GID=991
    volumes:
      - ./data:/data
    ports:
      - "8008:8008"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: synapse-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user -d synapse"]
      interval: 5s
      timeout: 5s
      retries: 5

EOF

# ==========================================
# 3. Generate Initial Synapse Config
# ==========================================

echo "Generating initial Synapse keys and config..."
# We run this to get the signing keys and the random secrets
docker compose run --rm --no-deps synapse generate

# Fix permissions on generated files (Docker creates them as UID 991)
chown -R "$(id -u):$(id -g)" data/

if [ ! -f data/homeserver.yaml ]; then
    echo "Error: homeserver.yaml was not generated."
    exit 1
fi

# ==========================================
# 4. Extract Secrets & Overwrite Config
# ==========================================

echo "Extracting secrets from generated config..."
# We extract the secrets generated by Synapse to inject into our custom config
REG_SECRET=$(grep "registration_shared_secret:" data/homeserver.yaml | awk '{print $2}' | tr -d '"')
MAC_SECRET=$(grep "macaroon_secret_key:" data/homeserver.yaml | awk '{print $2}' | tr -d '"')
FORM_SECRET=$(grep "form_secret:" data/homeserver.yaml | awk '{print $2}' | tr -d '"')

echo "Applying Will Lewis's performance tuning and PostgreSQL config..."

# Create the new optimized homeserver.yaml
cat > data/homeserver.yaml <<EOF
server_name: "$SERVER_NAME"
pid_file: "/data/homeserver.pid"

# Secrets (Preserved from generation)
registration_shared_secret: "$REG_SECRET"
macaroon_secret_key: "$MAC_SECRET"
form_secret: "$FORM_SECRET"
signing_key_path: "/data/$SERVER_NAME.signing.key"

# Serve federation well-known so Traefik just proxies through
serve_server_wellknown: true

# Database Configuration (PostgreSQL)
database:
  name: psycopg2
  args:
    user: synapse_user
    password: "$DB_PASSWORD"
    database: synapse
    host: postgres
    cp_min: 1
    cp_max: 25

# Network Listeners
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::', '0.0.0.0'] # Open to Docker network
    resources:
      - names: [client, federation]
        compress: false
  - port: 9000
    type: metrics
    bind_addresses: ['0.0.0.0']

# Logging
log_config: "/data/$SERVER_NAME.log.config"

# Performance & Features (From the Guide)
enable_metrics: true
report_stats: true

enable_media_repo: true
media_store_path: "/data/media_store"
max_upload_size: 500M
media_retention:
  local_media_lifetime: 45d
  remote_media_lifetime: 45d

presence:
  enabled: false

# Cache Tuning (Erik Johnston's recommendations)
event_cache_size: 200K
federation_rc_concurrent: 3
federation_rc_reject_limit: 50
federation_rc_sleep_delay: 500
federation_rc_sleep_limit: 10
federation_rc_window_size: 10000
rc_message_burst_count: 10
rc_messages_per_second: 10
gc_thresholds: [1500, 20, 10]
caches:
  global_factor: 5
  expire_caches: true
  cache_entry_ttl: 10m
  cache_autotuning:
    max_cache_memory_usage: 600M
    target_cache_memory_usage: 400M
    min_cache_ttl: 30s
EOF

# ==========================================
# 5. Launch
# ==========================================

# Set ownership back to Synapse's UID/GID so it can write to /data
chown -R 991:991 data/

echo "Starting the Matrix Server..."
docker compose up -d

echo "----------------------------------------------------------------"
echo "Deployment Complete!"
echo "Domain: $SERVER_NAME"
echo "Location: $(pwd)"
echo "----------------------------------------------------------------"
echo ""
echo "Synapse is now initializing its database for the first time."
echo "This can take a minute or two. Watch the logs with:"
echo ""
echo "  sudo docker logs synapse -f"
echo ""
echo "Once you see 'Synapse now listening on TCP port 8008', it's ready."
echo ""
echo "NEXT STEP: Create your first Admin user:"
echo ""
echo "  docker exec -it synapse register_new_matrix_user -c /data/homeserver.yaml -u <username> -p <password> --admin"
echo "----------------------------------------------------------------"
